"""Golden-file cases for fault classification — one JSON file per scenario.

Same idea as test_decoder.py's golden file (run the real code, compare against a
committed expected result), but applied only to the fields `describe()` *derives*:
`zone`, `severity`, `deferrable`.

Why not the descriptions too: those are read verbatim out of
obd_reader/data/dtc_generic.json, so restating them here would copy the catalog into a
second file and mean editing both to add one code. `zone` is computed from the code
prefix, which is the part that can actually drift — PR #6 rewrote exactly that logic.

Why one file per scenario rather than one big table: a case is a story ("EVAP leaks are
emissions, not exhaust") and the file keeps that story next to the codes that prove it.
Adding a case is a new file, not a new test function.

The cases are HAND-WRITTEN from the OBD-II code ranges and must never be regenerated by
running describe() — see test_files/faults/README.md for why that would launder bugs
into "expected".

Runs standalone (python3 tests/test_faults_golden.py) or under pytest.
"""

import glob
import json
import os
import sys

# Why: make the package importable when the test is run directly from tests/.
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from obd_reader.faults import describe

# The cases sit beside this file. Why co-located: nothing outside this test reads them,
# so reaching up to a repo-level test_files/ was indirection for its own sake. Resolved
# from __file__ rather than the cwd so the suite runs from anywhere.
# (Contrast test_files/sample_obd_output.json, which cannot move here — reader.py's
# FixtureReader loads it at runtime, so it is not purely test data.)
CASES_DIR = os.path.join(os.path.dirname(__file__), "cases")


def _load_cases() -> list[tuple[str, dict]]:
    """Read every case file, newest naming order irrelevant — sorted for stable output.

    Why a helper: the standalone runner and pytest both want the same list, and sorting
    keeps failure output in a predictable order so a diff of two runs is readable.
    """
    paths = sorted(glob.glob(os.path.join(CASES_DIR, "*.json")))
    return [(os.path.basename(p), json.load(open(p, encoding="utf-8"))) for p in paths]


def test_golden_fault_cases():
    """Check every code in every case file against what describe() actually returns.

    Why it collects all failures instead of stopping at the first: a zone-rule change
    usually breaks several codes at once, and seeing the whole set tells you whether you
    broke one family or the entire prefix table. Stopping at the first mismatch hides
    the shape of the breakage (TEST-4).
    """
    cases = _load_cases()

    # Why this guard: a glob that silently matches nothing would make this test pass
    # while checking absolutely nothing — the worst kind of green.
    if not cases:
        raise AssertionError(
            f"No golden case files found in {CASES_DIR}. Expected at least one *.json; "
            "either the fixtures were deleted or CASES_DIR is pointing somewhere wrong."
        )

    failures: list[str] = []
    checked = 0

    for filename, data in cases:
        for entry in data.get("codes", []):
            code = entry["code"]
            got = describe(code)
            # Keys starting with "_" are commentary (_why), never assertions.
            expected_fields = {
                k: v for k, v in entry.items() if k != "code" and not k.startswith("_")
            }
            for field, want in expected_fields.items():
                checked += 1
                actual = got.get(field)
                if actual != want:
                    failures.append(
                        f"  {filename} :: {code} :: {field}\n"
                        f"      expected: {want!r}\n"
                        f"      actual:   {actual!r}"
                    )

    if failures:
        raise AssertionError(
            f"{len(failures)} golden fault expectation(s) failed "
            f"({checked} checked across {len(cases)} case files):\n"
            + "\n".join(failures)
            + "\n\n  Likely cause: a zone prefix rule, a severity set, or a catalog entry "
            "changed.\n  Fix the CODE if the case file is right. Only edit a case file if "
            "you can point\n  to the OBD-II range that says otherwise — never 'update' it "
            "to match new output."
        )


def test_case_files_are_well_formed():
    """Catch a malformed case file as a fixture error, not as a confusing failure.

    Why: an entry naming no expected fields at all (a bare {"code": ...}) is compared
    against nothing by the test above and passes green — that is the one genuine silent
    pass, and this check is the only thing standing in front of it. A typo'd field name
    does fail above, but as `expected 'emissions' / actual None`, which sends you reading
    describe() instead of the typo three feet away; reporting it as an unknown field is
    the difference between a five-second fix and a confusing hunt. A missing "code" key
    would raise a bare KeyError naming no file at all.
    """
    valid_fields = {"zone", "severity", "deferrable", "description"}
    problems: list[str] = []

    for filename, data in _load_cases():
        if not data.get("codes"):
            problems.append(f"  {filename}: no 'codes' list (or it is empty)")
            continue
        for i, entry in enumerate(data["codes"]):
            if "code" not in entry:
                problems.append(f"  {filename}: entry {i} has no 'code' key")
                continue
            asserted = {
                k for k in entry if k != "code" and not k.startswith("_")
            }
            if not asserted:
                problems.append(
                    f"  {filename} :: {entry['code']}: asserts nothing — "
                    "give it at least one expected field"
                )
            unknown = asserted - valid_fields
            if unknown:
                problems.append(
                    f"  {filename} :: {entry['code']}: unknown field(s) {sorted(unknown)}; "
                    f"describe() returns {sorted(valid_fields)}"
                )

    if problems:
        raise AssertionError("Malformed golden case file(s):\n" + "\n".join(problems))


if __name__ == "__main__":
    import traceback
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"PASS {fn.__name__}")
        except Exception:
            failed += 1
            print(f"FAIL {fn.__name__}")
            traceback.print_exc()
    print(f"\n{len(fns) - failed}/{len(fns)} passed")
    sys.exit(1 if failed else 0)
